### ISSUE TITLE
Error when attempting to execute run.bat

### ISSUE THREAD

**Issue by Kuroseji** [HaW-Tagger/HWtagger#1]
When I attempt to execute run.bat after running install.bat I get the following error.
```
H:\HWtagger> .\run.bat
Traceback (most recent call last):
  File "H:\HWtagger\pyside6_ui.py", line 1, in <module>
    import DatabaseCreationView
  File "H:\HWtagger\DatabaseCreationView.py", line 3, in <module>
    from PySide6.QtCore import Slot
ModuleNotFoundError: No module named 'PySide6'
```
I tried googling around for a solution but nothing is working for me.  Anyone got any ideas or guidance? Running Windows 10 and tried this with Python 3.10.11 and Python 3.11.3.

**Comment by kukaiN** [comment]
You probably don't have that library installed. Make sure to follow the instruction and install the requirements. Were there any errors with the install?  Or you can also run install_sanity_check.bat, and check for anything there as well.

**Comment by Kuroseji** [comment]
Thank for the reply. I think something went wrong the first time I did the install and I didn't think to tray again from scratch until after I read your comment.
