### ISSUE TITLE
danbooru.donmai.us is blocked in my country, and it causes application to freeze for some time when it tries to access it

### ISSUE THREAD

**Issue by MarvyD** [HaW-Tagger/HWtagger#7]
When VPN is enabled everything is working fine. I suggest adding an option to use a proxy (more convenient than running VPN for all Python applications) , and an option to disable tag lookup for people who don't have a proxy or VPN (Maybe it already exists but i haven't found it). 

> Traceback (most recent call last):
>   File "D:\AI\HWtagger\.venv\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
>     self._validate_conn(conn)
>   File "D:\AI\HWtagger\.venv\lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
>     conn.connect()
>   File "D:\AI\HWtagger\.venv\lib\site-packages\urllib3\connection.py", line 730, in connect
>     sock_and_verified = _ssl_wrap_socket_and_match_hostname(
>   File "D:\AI\HWtagger\.venv\lib\site-packages\urllib3\connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
>     ssl_sock = ssl_wrap_socket(
>   File "D:\AI\HWtagger\.venv\lib\site-packages\urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
>     ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
>   File "D:\AI\HWtagger\.venv\lib\site-packages\urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
>     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
>   File "D:\AI\HWtagger\.venv\lib\site-packages\cloudscraper\__init__.py", line 100, in wrap_socket
>     return self.ssl_context.orig_wrap_socket(*args, **kwargs)
>   File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 513, in wrap_socket
>     return self.sslsocket_class._create(
>   File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1071, in _create
>     self.do_handshake()
>   File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1342, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1007)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\AI\HWtagger\.venv\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
>     response = self._make_request(
>   File "D:\AI\HWtagger\.venv\lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
>     raise new_e
> urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1007)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "D:\AI\HWtagger\.venv\lib\site-packages\requests\adapters.py", line 667, in send
>     resp = conn.urlopen(
>   File "D:\AI\HWtagger\.venv\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
>     retries = retries.increment(
>   File "D:\AI\HWtagger\.venv\lib\site-packages\urllib3\util\retry.py", line 519, in increment
>     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='danbooru.donmai.us', port=443): Max retries exceeded with url: /wiki_pages.json?search%5Btitle%5D=mechanical_arms (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1007)')))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\AI\HWtagger\DatabaseViewBase.py", line 152, in data
>     return self.image.tooltip(tag)
>   File "D:\AI\HWtagger\classes\class_image.py", line 1119, in tooltip
>     wiki = tag.wiki()
>   File "D:\AI\HWtagger\classes\class_elements.py", line 876, in wiki
>     response = scraper.get(url=url, headers=HTTP_HEADERS)
>   File "D:\AI\HWtagger\.venv\lib\site-packages\requests\sessions.py", line 602, in get
>     return self.request("GET", url, **kwargs)
>   File "D:\AI\HWtagger\.venv\lib\site-packages\cloudscraper\__init__.py", line 259, in request
>     self.perform_request(method, url, *args, **kwargs)
>   File "D:\AI\HWtagger\.venv\lib\site-packages\cloudscraper\__init__.py", line 192, in perform_request
>     return super(CloudScraper, self).request(method, url, *args, **kwargs)
>   File "D:\AI\HWtagger\.venv\lib\site-packages\requests\sessions.py", line 589, in request
>     resp = self.send(prep, **send_kwargs)
>   File "D:\AI\HWtagger\.venv\lib\site-packages\requests\sessions.py", line 703, in send
>     r = adapter.send(request, **kwargs)
>   File "D:\AI\HWtagger\.venv\lib\site-packages\requests\adapters.py", line 698, in send
>     raise SSLError(e, request=request)
> requests.exceptions.SSLError: HTTPSConnectionPool(host='danbooru.donmai.us', port=443): Max retries exceeded with url: /wiki_pages.json?search%5Btitle%5D=mechanical_arms (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1007)')))

Edit: Even when VPN is enabled app still occasionally freezes if i hover over some tag most likely because it takes too long to connect sometimes, there aren't any errors displayed in terminal in this case. Tooltip activation time is pretty low, so app sometimes freezes when i hover over tag just to add or remove it

**Comment by PhoenixAscencio** [comment]
Hello, for now I added a parameter to deactivate it entirely. I don't think we will use a proxy for now since I never looked into what a proxy is. Thanks for the feedback.
