### ISSUE TITLE
Error when trying to move image into a new group

### ISSUE THREAD

**Issue by wishuponacupoftea** [HaW-Tagger/HWtagger#8]
My system:
Windows 11 23H2
32GB RAM
RTX 4090

Steps to reproduce:

git clone the latest version (commit e5595e94b14f35e45348a458f9f724299ae8f2cb)
run the setup .bat
install goes fine, a few warnings about pip 23.0.1 being outdated, but I think that is normal
create identical file structure as shown in Youtube tutorial: https://www.youtube.com/watch?v=IvLH6fZm1wU
At 13:40 in the video, Add Selection To Group button is clicked

Nothing happens, the error in the logs:

```
Traceback (most recent call last):
  File "C:\AIArtProject\Git\PortableGit\HWtagger\DatabaseViewBase.py", line 1181, in add_selection_to_group
    image_index = int(self.listView_groups.model().db_index(w_index))
  File "C:\AIArtProject\Git\PortableGit\HWtagger\DatabaseViewBase.py", line 470, in db_index
    return self.itemData(index)[0]
KeyError: 0
```

This is not reproduceable on commit 0409caa92aeafc97bebda9cb28698c5dbb3a1e68 from June 25, which works fine.

I would really like to use the newest version, thank you very much!

**Comment by PhoenixAscencio** [comment]
Hello, the issue has been fixed, it was simply a typo due to a bad copypaste, I will be more careful in the future (hopefully :D). thanks for the feedback.
